-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;port=1521;service_name=XEPDB1

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SEQUENCE departments_seq INCREMENT 10 MINVALUE 1 MAXVALUE 9990 START 280;
CREATE SEQUENCE employees_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 207;
CREATE SEQUENCE locations_seq INCREMENT 100 MINVALUE 1 MAXVALUE 9900 START 3300;
