-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;port=1521;service_name=XEPDB1

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS secure_employees ON employees CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_secure_employees() RETURNS trigger AS $BODY$
BEGIN
  CALL secure_dml();
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER secure_employees
	BEFORE INSERT OR UPDATE OR DELETE ON employees FOR EACH STATEMENT
	EXECUTE PROCEDURE trigger_fct_secure_employees();

DROP TRIGGER IF EXISTS update_job_history ON employees CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_update_job_history() RETURNS trigger AS $BODY$
BEGIN
  CALL add_job_history(OLD.employee_id, OLD.hire_date, statement_timestamp(),
                  OLD.job_id, OLD.department_id);
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER update_job_history
	AFTER UPDATE OF job_id,department_id ON employees FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_update_job_history();

